### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by jeanyeeee** [jeanyeeee/dining-rc-app#19]
Reviews:

- [x] Make sure that all details can be seen

- [x] Check that Update and deletion works!!!

**Comment by Zhongli5712** [comment]
Deletion works, Update code must import setDoc function in EditScreen.js, after added, test ok. check 22/07 update

**Comment by jeanyeeee** [comment]
@Zhongli5712 For me, the edit does not do anything when press submit!
